M48
; DRILL file {KiCad 9.0.1} date 2025-05-24T18:06:30+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-24T18:06:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X193.5Y-79.0
X193.5Y-88.0
T2
X3.475Y-3.475
X159.0Y-74.0
X159.0Y-93.0
X191.5Y-55.0
X191.5Y-110.0
M30
